### ISSUE TITLE
Elements() raises exception

### ISSUE THREAD

**Issue by newville** [vasole/fisx#4]
on a clean install of the master branch of fisx with Anaconda Python 2.7.11 on Mac OSX (10.11):

```
Python 2.7.11 |Anaconda 2.4.1 (x86_64)| (default, Dec  6 2015, 18:57:58) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> from fisx import Elements, version 
>>> version()
'1.0.6'
>>> elems  = Elements()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "python/cython/_fisx.pyx", line 288, in fisx._fisx.PyElements.__cinit__ (/Users/Newville/Codes/fisx_sole/python/cython/_fisx.cpp:5189)
    self.thisptr = new Elements(directoryName)
 is not a valid transition
```

**Comment by vasole** [comment]
Thanks for the report. Please, can you provide:
- How was fisx build/installed? (Using conda install or python setup.py ... or pip install .) 
- What is the result of python -m fisx.tests.testAll

In order to check if it is a problem with the cython version, please can you build the library from a clean checkout passing the option --no-cython to setup.py

**Comment by newville** [comment]
@vasole As I said in the original report:

```
on a clean install of the master branch of fisx with Anaconda Python 2.7.11 on Mac OSX (10.11)
```

That is, I built from the source tree with the latest master branch from github, using the build instructions for the git repository  of `python setup.py install`.

A `python -m fisx.tests.testAll` reports: 

   testDataDirectoryPresence (testDataDir.testDataDir) ... ok
   testDataFilePresence (testDataDir.testDataDir) ... ok
   testDocDirectoryPresence (testDataDir.testDataDir) ... ok
   testEPDL97BindingVersusPyMcaEPDL97Binding (testEPDL97.testEPDL97) ... ok
   testEPDL97Import (testEPDL97.testEPDL97) ... ok
   testEPDL97MuVersusPyMcaEPDL97Mu (testEPDL97.testEPDL97) ... ok
   testEPDL97PartialVersusPyMcaPartial (testEPDL97.testEPDL97) ... 
   Photoelectric weights OK at default energies
   Photoelectric weights OK at any energy
   ok
   testSimpleSpecfileImport (testSimpleSpecfile.testSimpleSpecfile) ... ok
   testSimpleSpecfileReading (testSimpleSpecfile.testSimpleSpecfile) ... ok
   testSimpleSpecfileReadingCompatibleWithUserLocale (testSimpleSpecfile.testSimpleSpecfile) ... ok
   testSimpleSpecfileVersusPyMca (testSimpleSpecfile.testSimpleSpecfile) ... ok

---

   Ran 11 tests in 26.283s

   OK

which suggests none of the tests create an instance of Elements().  Indeed, a grep on the test code confirms that suspicion.  

A clean install with `python setup.py --no-cython install` does not work either -- same problem.

**Comment by vasole** [comment]
- I was suspecting a problem with the data location, therefore I asked to run the tests.
- I have added a specific test for your problem and the complete example to the test suite (pull request #10)
- Continuous integration tests pass for linux, **MacOS** and windows

I will have to get an actual Mac and install anaconda, because up to now I have been unable to reproduce the error.

**Comment by vasole** [comment]
@newville 

The error message can only come from a single place in fisx_shell.cpp. However, the offending transition is not reported in the message as it should (tested at my side). I have added a printout of the error to the C++ standard output in order to get more information.

Please try to build from current master branch and report the message.

**Comment by newville** [comment]
@vasole I played around with this quite a bit over the past couple days, trying to track down in the C++ code where the problem was from.  It is definitely while reading the shell transition data.  In fact, by classic "print statement" debugging with the `labels` in `Shell::setRadiativeTransitions`, I saw some garbled looking values when it got to the 'L1Q3' label.  (And, really Q shell? Do those exist?).

Anyway, that inspired me to look at the data files in `fisx_data` that are being parsed.   Sure enough, L1Q3 is at the end of the line of `EADL97_LShellRadiativeRates.dat`.  And, sure enough, the files in the git repository have DOS line endings.  And,  sure enough, the code to parse these files as Spec files (really?) does not account for that.    Simply changing the line endings to UNIX line endings on these files means that the data can be read, and `Elements()` succeeds. 

Sorry, but this so very elegantly illustrates my point about using data tables in SQLite or other real database systems that I could not have possibly invented a better example.   XRF simulation code should not be parsing plain text files of fundamental constants at run-time. 

Anyway, at least now I understand how I can use fisx as a reference for testing other code.

**Comment by vasole** [comment]
The files in the repository are supposed to have \n endings. The 
contrary would be a bug at my side and the tests would not pass as they 
do in all the platforms with their default settings. As you can 
appreciate, I have turned continuous integration on following your 
report.

I receive them with \n and I send them with \n irrespectively of being 
in linux, Mac or windows.

It would be convenient to know your git settings, in particular for 
autocrlf

**Comment by vasole** [comment]
@newville 

I would like to ask you a last check.

Without changing anything at your side, perform a build from a fresh 
checkout.

I have added a .gitattributes file to the project to make sure the 
settings at the user side do not modify the files.

**Comment by vasole** [comment]
@newville

Irrespectively of .gitattributes preventing file modification on 
checkout, the user can **always** modify the files with too smart 
editors. PR #11 deals with that.

I do agree that is better to parse the files at build time and not at 
run-time, but in your case that would not have helped because you were 
already modifying the files prior to the build. As a matter of fact, if 
you would have used the released source code instead of the checkout 
everything would have worked.

Thanks for the report. It deserves a dedicated release to prevent 
problems with introduction of CR by the user when editing the files.

**Comment by newville** [comment]
Yes, that appears to work. 

Actually, I did not alter the files, that's how they landed on my system with a git clone.   Go figure.

FWIW, I think you still misunderstand my point.  I am definitely saying to not build the database at runtime.   But I am also saying to not build the database at build time.  I am saying to build it _EXACTLY ONCE_ at distribute that compiled, portable, sqlite database and the very simple code to extract data values which could be floats or integers or json strings that turn into arrays or dictionaries.    Really, I mean parse the text file exactly one time.

**Comment by vasole** [comment]
The alteration happens involuntarily following GIT settings. The surprising thing is that you were cloning to a Mac. On a windows computer the problem you encountered is much more likely. Anyways, it will not happen again. I am really grateful for your contribution.

I do not think I misunderstood your point. It is certainly safer and more efficient because one only parses once the data:
- If I would have distributed the data in binary form, you would not have experienced any trouble. 
- My parsing code is very slow and it would be faster to read binary data.

My point is that **somewhere** there must be a repository of original, not parsed (or minimally parsed) data from which all binary flavors (probably HDF5 or/and SQLite) can emerge. For instance, xraylib was not parsing EADL/EPDL97 directly as I was doing. It was taking my already extracted data. You can do the same, but, if I made a mistake, the mistake will propagate. I would be very pleased if you could consider reviewing my original EADL/EPDL97 file reader.

**Comment by newville** [comment]
@vasole   The sqlite database is at https://github.com/scikit-beam/XrayDB   This XrayDB does not yet include the EPDL97 data  -- it has been parsed from the original to python data structures, but has yet been entered into the database.  There is certainly more data and python methods to add, and a PR for a start at documentation.  Of course, any insight or involvement would be greatly appreciated.

The data from various sources can be parsed and entered into the database exactly once, ever.  The database then becomes the reference source for all use, including any updates that might be needed.   We do keep the original data and parsing code for historical purposes, but that code does not need to be guaranteed to run without modification on any more than exactly one machine ever.   The point is that the sqlite version is more portable than plain text files, and it comes with a standard API for extracting data.  Once the data is in the database, how it got there is an historical detail.
